server:
  port: 80
spring:
  datasourse:
    url: jdbc:mysql://localhost:3306/BlogDemo?useSSL=false&serverTimezone=UTC
    username: root
    password: liulu20040522
    drive-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml